---
# TODO: fill this in
- name: ensure video driver
  shell: echo foo

- name: restart eod
  command: "{{ eod_install_directory }}/bin/otecs restart"
  when: install_eod

# TODO: we need to figure out a clean way to killall the gdm processes, *then* run this step
- name: restart gdm
  command: restart prefdm
  when: install_eod
