---
- name: Install all dependencies
  yum:
    name: "{{item}}"
    state: present
    disable_gpg_check: yes
  with_items:
    - "{{ gocd_rpms }}"
  notify:
    - restart go-agent

- name: Get GoCD RPM
  get_url:
    url: "{{ gocd_agent_package_url }}"
    dest: /tmp/

- name: Install GoCD Agent
  yum:
    name: "{{ gocd_agent_package_name }}"
    state: present
  notify:
    - restart go-agent

- name: Ensure working directory exists
  file:
    state: directory
    dest: "{{ gocd_agent_work_dir }}"
    owner: go
    group: go
    mode: 0755
  notify:
    - restart go-agent

- name: Replace go-agent file
  template:
    src: go-agent
    dest: /etc/default/go-agent
  notify:
    - restart go-agent

- name: Start go-agent
  service:
    name: go-agent
    state: started
