---
jdk_packages:
  - java-1.8.0-openjdk
  - java-1.8.0-openjdk-devel
  - libselinux-python

java_deploy_options:
jre_lib_path: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-0.b17.el6_7.x86_64/jre/lib
java_home_path: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-0.b17.el6_7.x86_64/jre
