# main.yml - Activate EPEL
---
- name: Get EPEL repo
  get_url:
    url: "http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm"
    dest: /tmp/
  retries: 3
  delay: 15

- name: Install EPEL repo
  command: "rpm -ivh /tmp/epel-release-6-8.noarch.rpm"
  args:
    creates: /etc/yum.repos.d/epel.repo

- name: Import the EPEL GPG key
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6"
    state: present
