---
dependencies:
  - {role: python, when: "custom_repo"}
  - {role: python-build, when: "not custom_repo"}
  - role: jdk
  - {role: epel, when: "use_epel"}
  - role: postgresql-client
  - role: odbc
  - role: jdbc
