---
gocd_server_package_url: https://download.go.cd/gocd-rpm/go-server-15.2.0-2248.noarch.rpm
gocd_server_package_name: /tmp/go-server-15.2.0-2248.noarch.rpm
gocd_server_work_dir: /var/lib/go-server
gocd_server_port: 8153
gocd_server_ssl_port: 8154
gocd_admin_password: W6ph5Mm5Pz8GgiULbPgzG37mj9g= # "password"
