# main.yml
---
#- name: Add mpapis public key
#  shell: "curl -sSL https://rvm.io/mpapis.asc | gpg --import -"

- name: Get mpapis.asc
  get_url:
    url: https://rvm.io/mpapis.asc
    dest: /tmp/mpapis.asc

- name: Import key
  command: "gpg --import /tmp/mpapis.asc"
  register: import_key
  failed_when: import_key.rc != 0 and "not changeds" not in import_key.stderr
  changed_when: import_key.rc == 0

- name: Get script file
  get_url:
    url: https://get.rvm.io/
    dest: /tmp/rvm-installer.sh

- name: Configure rvm-installer
  file:
    dest: /tmp/rvm-installer.sh
    mode: 0755

#- name: Import GPG Keys
#  command: 'gpg --keyserver hkp://keys.gnupg.net:80 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3'
#  changed_when: false
#  ignore_errors: yes

- name: Install RVM and stable Ruby
  command: "/tmp/rvm-installer.sh stable --ruby"
  args:
    creates: /usr/local/rvm/bin/rvm

- name: Ensure /etc/rvmrc is available
  file:
    dest: /etc/rvmrc
    mode: 0664
